apiVersion: v1
data:
  dbname: library
  host: mysql.database:3306
kind: ConfigMap
metadata:
  creationTimestamp: "2024-05-09T08:05:03Z"
  name: restapi-cm
  namespace: restapi
  resourceVersion: "40672"
  uid: b7e55d51-6ece-44f7-abb7-b31f78db1e06
