apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: restapi-deploy
  name: restapi-service
  namespace: restapi
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: restapi-deploy
status:
  loadBalancer: {}
